/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_darielsevilla;

import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HP
 */
public class Principal extends javax.swing.JFrame {

    private Administrador admin;
    private Dba database;

    public Principal() {
        initComponents();
        admin = new Administrador("./Lenguajes.txt");
        database = new Dba("./ExamenII1.accdb");

        admin.lea();
        fillTree();
    }

    public void fillTree() {
        DefaultTreeModel modelo = (DefaultTreeModel) jt_arbol.getModel();

        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Lenguajes");
        modelo.setRoot(raiz);
        System.out.println();
        for (Lenguaje l : admin.getLenguajes()) {
            DefaultMutableTreeNode lenguaje = new DefaultMutableTreeNode(l);
            DefaultMutableTreeNode creadores = new DefaultMutableTreeNode("Creadores");
            DefaultMutableTreeNode palabras = new DefaultMutableTreeNode("Palabras Reservadas");
            DefaultMutableTreeNode informacion = new DefaultMutableTreeNode("Informacion general");

            raiz.add(lenguaje);
            lenguaje.add(creadores);
            lenguaje.add(palabras);
            lenguaje.add(informacion);

            //añadir creadores al arbol
            for (Creador c : l.getCreadores()) {
                creadores.add(new DefaultMutableTreeNode(c));
            }

            //añadir palabras al arbol
            for (Palabras p : l.getPalabrasReservadas()) {
                palabras.add(new DefaultMutableTreeNode(p));
            }

            //añadir datos adicionales
            String sensitive = "";
            if (l.isCaseSensisitve()) {
                sensitive = "Si";
            } else {
                sensitive = "No";
            }

            SimpleDateFormat formato = new SimpleDateFormat("dd-mm-yyyy");
            informacion.add(new DefaultMutableTreeNode("Case sensitive - " + sensitive));
            informacion.add(new DefaultMutableTreeNode(formato.format(l.getFecha())));
            informacion.add(new DefaultMutableTreeNode(l.getPersonas()));
        }
        modelo.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_menu = new javax.swing.JPopupMenu();
        mi_subir = new javax.swing.JMenuItem();
        mi_eliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_descripcion = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_creadores = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_datos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_palabras = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt_subir = new javax.swing.JButton();

        mi_subir.setText("subir");
        mi_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_subirActionPerformed(evt);
            }
        });
        pop_menu.add(mi_subir);

        mi_eliminar.setText("eliminar");
        mi_eliminar.setToolTipText("");
        mi_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_eliminarActionPerformed(evt);
            }
        });
        pop_menu.add(mi_eliminar);
        pop_menu.add(jSeparator1);

        mi_descripcion.setText("ver detalles");
        mi_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_descripcionActionPerformed(evt);
            }
        });
        pop_menu.add(mi_descripcion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Examen II");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jt_arbol.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lenguajes");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_arbol);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 152, 493));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Detalles:");

        jt_creadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Nacionalidad", "Profesion"
            }
        ));
        jScrollPane2.setViewportView(jt_creadores);

        jt_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Case Sensitive", "Fecha creacion", "Personas q lo usan"
            }
        ));
        jScrollPane3.setViewportView(jt_datos);

        jt_palabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Palabra", "Sinonimo", "Significado Gramatical"
            }
        ));
        jScrollPane4.setViewportView(jt_palabras);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del lenguaje:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Creadores:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Datos adicionales:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Palabras reservadas:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 60, -1, -1));

        bt_subir.setText("Subir en la base de datos");
        bt_subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_subirMouseClicked(evt);
            }
        });
        jPanel1.add(bt_subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 563, 390, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolMouseClicked
        DefaultTreeModel modelo = (DefaultTreeModel) jt_arbol.getModel();
        if (SwingUtilities.isRightMouseButton(evt)) {
            int x = jt_arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_arbol.setSelectionRow(x);
            pop_menu.show(jt_arbol, evt.getX(), evt.getY());
            
        }
    }//GEN-LAST:event_jt_arbolMouseClicked

    private void mi_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_subirActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("archivos de texto", "txt");
        jfc.addChoosableFileFilter(filter);
        int x = jfc.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            String[] check = f.toString().split("\\.");
            if (check[check.length - 1].equals("txt")) {
                Administrador admin2 = new Administrador();
                admin2.setFile(f);
                admin2.lea();
                for (Lenguaje l : admin2.getLenguajes()) {
                    admin.getLenguajes().add(l);
                }
                fillTree();
            } else {
                JOptionPane.showMessageDialog(null, "Tipo de archivo invalido");
            }
        }
    }//GEN-LAST:event_mi_subirActionPerformed

    private void mi_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_eliminarActionPerformed
        DefaultMutableTreeNode nodoActual = (DefaultMutableTreeNode) jt_arbol.getSelectionPath().getLastPathComponent();

        Object actual = nodoActual.getUserObject();

        if (actual instanceof Lenguaje) {
            admin.getLenguajes().remove((Lenguaje) actual);

            fillTree();

        }
    }//GEN-LAST:event_mi_eliminarActionPerformed

    private void mi_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_descripcionActionPerformed
        try {
            DefaultMutableTreeNode nodoActual = (DefaultMutableTreeNode) jt_arbol.getSelectionPath().getPathComponent(1);

            Object actual = nodoActual.getUserObject();

            if (actual instanceof Lenguaje) {
                Lenguaje l = (Lenguaje) actual;
                llenarTablas(l);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No seleccione la raiz");
        }

    }//GEN-LAST:event_mi_descripcionActionPerformed

    private void bt_subirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_subirMouseClicked

        if (!jl_nombre.getText().equals("")) {
            try {
                database.conectar();
                
                
                database.query.execute("DELETE FROM Lenguaje WHERE nombre like '" + jl_nombre.getText() + "'");
                database.commit();
                database.query.execute("DELETE FROM Creadores WHERE Lenguaje = '" + jl_nombre.getText() + "'");
                database.commit();
                database.query.execute("DELETE FROM PalabrasReservadas WHERE Lenguaje = '" + jl_nombre.getText() + "'");
                database.commit();
                database.desconectar();
                DefaultTableModel creators = (DefaultTableModel) jt_creadores.getModel();
                DefaultTableModel info = (DefaultTableModel) jt_datos.getModel();
                DefaultTableModel palabras = (DefaultTableModel) jt_palabras.getModel();
               
                String temp = "INSERT INTO Lenguaje VALUES ('" + jl_nombre.getText() + "','" + ((String) info.getValueAt(0, 1)) + "','" + ((String) info.getValueAt(0, 0)) + "','" + ((String) info.getValueAt(0, 2)) + "')";
                database.conectar();
                database.query.execute(temp);
                database.commit();
                for (int i = 0; i < creators.getRowCount(); i++) {
            
                    database.query.execute("INSERT INTO Creadores values('" + ((String) creators.getValueAt(i, 0)) + "', '" + ((String) creators.getValueAt(i, 1)) + "', '" + ((String) creators.getValueAt(i, 2)) + "','" + jl_nombre.getText() + " ')");
                    database.commit();
                }

                for (int i = 0; i < palabras.getRowCount(); i++) {

                    database.query.execute("INSERT INTO PalabrasReservadas VALUES ('" + ((String) palabras.getValueAt(i, 0)) + "','" + ((String) palabras.getValueAt(i, 1)) + "','" + ((String) palabras.getValueAt(i, 2)) + "','" + jl_nombre.getText() + "')");
                    database.commit();
                }
                database.desconectar();
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_bt_subirMouseClicked

    public void llenarTablas(Lenguaje l) {
        jl_nombre.setText(l.getNombre());
        DefaultTableModel creators = (DefaultTableModel) jt_creadores.getModel();
        DefaultTableModel info = (DefaultTableModel) jt_datos.getModel();
        DefaultTableModel palabras = (DefaultTableModel) jt_palabras.getModel();

        //resetear modelos
        creators.setRowCount(0);
        info.setRowCount(0);
        palabras.setRowCount(0);

        //agregar creadores
        for (Creador c : l.getCreadores()) {
            creators.addRow(new Object[]{c.getNombre(), c.getNacionalidad(), c.getProfesion()});
        }

        //agregar palabras
        for (Palabras p : l.getPalabrasReservadas()) {
            palabras.addRow(new Object[]{p.getPalabra(), p.getSinonimo(), p.getSignificado()});
        }

        //add info
        String sensitive = "";
        if (l.isCaseSensisitve()) {
            sensitive = "Si";
        } else {
            sensitive = "No";
        }
        SimpleDateFormat formato = new SimpleDateFormat("dd-mm-yyyy");
        info.addRow(new Object[]{sensitive, formato.format(l.getFecha()), l.getPersonas()});

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_subir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTable jt_creadores;
    private javax.swing.JTable jt_datos;
    private javax.swing.JTable jt_palabras;
    private javax.swing.JMenuItem mi_descripcion;
    private javax.swing.JMenuItem mi_eliminar;
    private javax.swing.JMenuItem mi_subir;
    private javax.swing.JPopupMenu pop_menu;
    // End of variables declaration//GEN-END:variables
}
